#server:
#  port: 9001
#  ssl:
#    enabled: false
#    key-store: keystore.p12
#    key-store-password: password
#    key-store-type: PKCS12
#    key-alias: bns-ssl

spring:
  h2:
    console:
      enabled: true
      path: h2-console
